defaultBaseImage: gcr.io/distroless/base:debug
builds:
  - id: debug
    flags:
      - -trimpath
    ldflags:
      - -X=github.com/google/go-containerregistry/cmd/crane/cmd.Version={{.Git.FullCommit}}
