name: container-build

on:
  push:
    tags: ['*']

env:
  KO_DEFAULTPLATFORMS: all

jobs:
  golang:
    name: Build the crane container image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with: 
          go-version: 1.21
          check-latest: true
      - name: Setup Ko
        uses: ko-build/setup-ko@v0.7
      - name: Build the crane-ish builder images
        run: |
          ko build -B github.com/google/go-containerregistry/cmd/crane -t latest -t ${{ env.GITHUB_SHA }} -t ${{ env.GITHUB_REF }}
          ko build -B github.com/google/go-containerregistry/cmd/gcrane -t latest -t ${{ env.GITHUB_SHA }} -t ${{ env.GITHUB_REF }}
          # ./cmd/krane is a separate module, so switch directories.
          cd ./cmd/krane
          ko build -B github.com/google/go-containerregistry/cmd/krane -t latest -t ${{ env.GITHUB_SHA }} -t ${{ env.GITHUB_REF }}
        with:
          KO_CONFIG_PATH: ${{ github.workspace }}/.ko/default/.ko.yaml
          # TODO: not sure if steps.string.outputs.lowercase is correct here, see also below
          KO_DOCKER_REPO: ghcr.io/${{ steps.string.outputs.lowercase }}
      - name: Build the crane-ish builder debug images
        run: |
          ko build -B github.com/google/go-containerregistry/cmd/crane  -t "debug"
          ko build -B github.com/google/go-containerregistry/cmd/gcrane -t "debug"
          # ./cmd/krane is a separate module, so switch directories.
          cd ${{ github.workspace }}/cmd/krane
          ko build -B github.com/google/go-containerregistry/cmd/krane -t "debug"
        with:
          KO_CONFIG_PATH: ${{ github.workspace }}/.ko/debug/.ko.yaml
      - name: Build the tag specific debug images
        run: |
          KO_DOCKER_REPO=gcr.io/${{ steps.string.outputs.lowercase }}/crane/debug  ko build --bare github.com/google/go-containerregistry/cmd/crane  -t latest -t ${{ env.GITHUB_SHA }} -t ${{ env.GITHUB_REF }}
          KO_DOCKER_REPO=gcr.io/${{ steps.string.outputs.lowercase }}/gcrane/debug ko build --bare github.com/google/go-containerregistry/cmd/gcrane -t latest -t ${{ env.GITHUB_SHA }} -t ${{ env.GITHUB_REF }}
          # ./cmd/krane is a separate module, so switch directories.
          cd ./cmd/krane
          KO_DOCKER_REPO=gcr.io/${{ steps.string.outputs.lowercase }}/krane/debug ko build --bare github.com/google/go-containerregistry/cmd/krane -t latest -t ${{ env.GITHUB_SHA }} -t ${{ env.GITHUB_REF }}
        with:
          KO_CONFIG_PATH: ${{ github.workspace }}/.ko/debug/.ko.yaml
